# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: procmessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11procmessage.proto\x12\x0e\x62iomaj.process\"\xfc\x02\n\x07Process\x12\x0c\n\x04\x62\x61nk\x18\x01 \x02(\t\x12\x0f\n\x07session\x18\x02 \x02(\t\x12\x0f\n\x07log_dir\x18\x03 \x02(\t\x12\x0b\n\x03\x65xe\x18\x04 \x02(\t\x12\x0c\n\x04\x61rgs\x18\x05 \x03(\t\x12\x30\n\x08\x65nv_vars\x18\x06 \x03(\x0b\x32\x1e.biomaj.process.Process.EnvVar\x12\x1b\n\x0cshell_expand\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x0c\n\x04name\x18\x08 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\t \x01(\t\x12\x11\n\tproc_type\x18\n \x01(\t\x12\x18\n\tis_docker\x18\x0b \x01(\x08:\x05\x66\x61lse\x12.\n\x06\x64ocker\x18\x0c \x01(\x0b\x32\x1e.biomaj.process.Process.Docker\x1a%\n\x06\x45nvVar\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\x1a\x30\n\x06\x44ocker\x12\r\n\x05image\x18\x01 \x02(\t\x12\x17\n\x08use_sudo\x18\x02 \x01(\x08:\x05\x66\x61lse\"\xe7\x01\n\tOperation\x12(\n\x07process\x18\x01 \x01(\x0b\x32\x17.biomaj.process.Process\x12:\n\x04type\x18\x02 \x02(\x0e\x32#.biomaj.process.Operation.OPERATION:\x07\x45XECUTE\x12.\n\x05trace\x18\x03 \x01(\x0b\x32\x1f.biomaj.process.Operation.Trace\x1a*\n\x05Trace\x12\x10\n\x08trace_id\x18\x01 \x02(\t\x12\x0f\n\x07span_id\x18\x02 \x02(\t\"\x18\n\tOPERATION\x12\x0b\n\x07\x45XECUTE\x10\x01')



_PROCESS = DESCRIPTOR.message_types_by_name['Process']
_PROCESS_ENVVAR = _PROCESS.nested_types_by_name['EnvVar']
_PROCESS_DOCKER = _PROCESS.nested_types_by_name['Docker']
_OPERATION = DESCRIPTOR.message_types_by_name['Operation']
_OPERATION_TRACE = _OPERATION.nested_types_by_name['Trace']
_OPERATION_OPERATION = _OPERATION.enum_types_by_name['OPERATION']
Process = _reflection.GeneratedProtocolMessageType('Process', (_message.Message,), {

  'EnvVar' : _reflection.GeneratedProtocolMessageType('EnvVar', (_message.Message,), {
    'DESCRIPTOR' : _PROCESS_ENVVAR,
    '__module__' : 'procmessage_pb2'
    # @@protoc_insertion_point(class_scope:biomaj.process.Process.EnvVar)
    })
  ,

  'Docker' : _reflection.GeneratedProtocolMessageType('Docker', (_message.Message,), {
    'DESCRIPTOR' : _PROCESS_DOCKER,
    '__module__' : 'procmessage_pb2'
    # @@protoc_insertion_point(class_scope:biomaj.process.Process.Docker)
    })
  ,
  'DESCRIPTOR' : _PROCESS,
  '__module__' : 'procmessage_pb2'
  # @@protoc_insertion_point(class_scope:biomaj.process.Process)
  })
_sym_db.RegisterMessage(Process)
_sym_db.RegisterMessage(Process.EnvVar)
_sym_db.RegisterMessage(Process.Docker)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {

  'Trace' : _reflection.GeneratedProtocolMessageType('Trace', (_message.Message,), {
    'DESCRIPTOR' : _OPERATION_TRACE,
    '__module__' : 'procmessage_pb2'
    # @@protoc_insertion_point(class_scope:biomaj.process.Operation.Trace)
    })
  ,
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'procmessage_pb2'
  # @@protoc_insertion_point(class_scope:biomaj.process.Operation)
  })
_sym_db.RegisterMessage(Operation)
_sym_db.RegisterMessage(Operation.Trace)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESS._serialized_start=38
  _PROCESS._serialized_end=418
  _PROCESS_ENVVAR._serialized_start=331
  _PROCESS_ENVVAR._serialized_end=368
  _PROCESS_DOCKER._serialized_start=370
  _PROCESS_DOCKER._serialized_end=418
  _OPERATION._serialized_start=421
  _OPERATION._serialized_end=652
  _OPERATION_TRACE._serialized_start=584
  _OPERATION_TRACE._serialized_end=626
  _OPERATION_OPERATION._serialized_start=628
  _OPERATION_OPERATION._serialized_end=652
# @@protoc_insertion_point(module_scope)
